/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.kamera.program;

import java.awt.HeadlessException;
import java.sql.Connection;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author rosyad
 */
public class pelanggan extends javax.swing.JFrame {
    
    private void kosongkan_form(){
        txtid.setEditable(true);
        txtid.setText(null);
        txtnama.setText(null);
        txtnohp.setText(null);
        txtalamat.setText(null);
        cbjeniskamera.setSelectedItem(this);
        txthargasewa.setText(null);
        txtwaktusewa.setText(null);
        txttotalharga.setText(null);
    }
    
    private void tampilkan_data(){
        
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No.");
        model.addColumn("No.ID");
        model.addColumn("Nama");
        model.addColumn("No.HP");
        model.addColumn("Alamat");
        model.addColumn("Jenis Kamera");
        model.addColumn("Harga Sewa");
        model.addColumn("Waktu Sewa");
        model.addColumn("Total Harga");
        
        String cari = txtpencarian.getText();
        try{
            int no = 1;
            String sql = "SELECT * FROM pelanggan WHERE Nama Like'%"+cari+"%'";
            java.sql.Connection conn = (Connection)sewakamera.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            
            while(res.next()){
                model.addRow(new Object[]{no++,res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5),res.getString(6),res.getString(7),res.getString(8)});
            }
            tabelpelanggan.setModel(model);
            
        }catch(SQLException e){
            System.out.println("Error : " + e.getMessage());
        }
    }

    /** Creates new form pelanggan */
    public pelanggan() {
        initComponents();
        tampilkan_data();
        kosongkan_form();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        txtnama = new javax.swing.JTextField();
        txtnohp = new javax.swing.JTextField();
        txtalamat = new javax.swing.JTextField();
        cbjeniskamera = new javax.swing.JComboBox<>();
        txthargasewa = new javax.swing.JTextField();
        txtwaktusewa = new javax.swing.JTextField();
        txttotalharga = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelpelanggan = new javax.swing.JTable();
        btsimpan = new javax.swing.JButton();
        btbaru = new javax.swing.JButton();
        bthitung = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btkeluar = new javax.swing.JButton();
        txtpencarian = new javax.swing.JTextField();
        bthapus = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Penyewaan Kamera");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("ROG Fonts", 2, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ROSYAD RENTAL KAMERA");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 430, 43));

        jLabel2.setText("No.ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 82, 61, -1));

        jLabel3.setText("Nama");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 122, 61, -1));

        jLabel4.setText("No.HP");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 162, -1, -1));

        jLabel5.setText("Alamat");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 205, -1, -1));

        jLabel6.setText("Jenis Kamera");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 240, -1, -1));

        jLabel7.setText("Harga sewa");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 272, -1, -1));

        jLabel8.setText("Waktu Sewa");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 301, -1, -1));

        jLabel9.setText("Total Harga");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 330, -1, -1));

        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });
        getContentPane().add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 82, 202, -1));
        getContentPane().add(txtnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 122, 261, -1));
        getContentPane().add(txtnohp, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 162, 204, -1));

        txtalamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtalamatActionPerformed(evt);
            }
        });
        getContentPane().add(txtalamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 202, 409, -1));

        cbjeniskamera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jenis Kamera", "CANON 60D", "CANON 1100D", "CANON 5D Mark II", "CANON 7D", "NIKON D3200", "NIKON D5200", "CANON EOS M3", "SONY A6500", "SONY A6400" }));
        cbjeniskamera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbjeniskameraActionPerformed(evt);
            }
        });
        getContentPane().add(cbjeniskamera, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 237, 146, -1));
        getContentPane().add(txthargasewa, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 272, 146, -1));
        getContentPane().add(txtwaktusewa, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 301, 146, -1));
        getContentPane().add(txttotalharga, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 331, 146, -1));

        tabelpelanggan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelpelanggan);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 820, 190));

        btsimpan.setText("Simpan");
        btsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsimpanActionPerformed(evt);
            }
        });
        getContentPane().add(btsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));

        btbaru.setText("Baru");
        btbaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbaruActionPerformed(evt);
            }
        });
        getContentPane().add(btbaru, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 74, -1));

        bthitung.setText("Hitung");
        bthitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bthitungActionPerformed(evt);
            }
        });
        getContentPane().add(bthitung, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, -1, -1));

        jLabel10.setText("/Jam");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 275, -1, -1));

        jLabel11.setText("/Jam");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 301, -1, -1));

        btkeluar.setText("Keluar");
        btkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btkeluarActionPerformed(evt);
            }
        });
        getContentPane().add(btkeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, 80, -1));

        txtpencarian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpencarianActionPerformed(evt);
            }
        });
        txtpencarian.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtpencarianKeyReleased(evt);
            }
        });
        getContentPane().add(txtpencarian, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 390, 190, -1));

        bthapus.setText("Hapus");
        bthapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bthapusActionPerformed(evt);
            }
        });
        getContentPane().add(bthapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 370, -1, -1));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("CARI");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 390, 30, 20));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kamera/4848c4be294c1f1d62a6a65ac7746ae6.jpg"))); // NOI18N
        jLabel13.setText("jLabel13");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 420, 630));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kamera/CAM@.jpg"))); // NOI18N
        jLabel14.setText("jLabel14");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btbaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbaruActionPerformed
        // TODO add your handling code here:
        kosongkan_form();
    }//GEN-LAST:event_btbaruActionPerformed

    private void bthitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bthitungActionPerformed
        // TODO add your handling code here:
        int lama = Integer.parseInt(txtwaktusewa.getText());
        int hargasewa = Integer.parseInt(txthargasewa.getText());
        int bayar = (lama*hargasewa);
        txttotalharga.setText(Integer.toString(bayar));
    }//GEN-LAST:event_bthitungActionPerformed

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    private void txtalamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtalamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtalamatActionPerformed

    private void btkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btkeluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btkeluarActionPerformed

    private void btsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsimpanActionPerformed
        // TODO add your handling code here:
        try{
            String sql = "INSERT INTO Pelanggan VALUES('"+txtid.getText()+"','"+txtnama.getText()+"','"+txtnohp.getText()+"','"+txtalamat.getText()+"','"+cbjeniskamera.getSelectedItem()+"','"+txthargasewa.getText()+"','"+txtwaktusewa.getText()+"','"+txttotalharga.getText()+"')";
            java.sql.Connection conn = (Connection)sewakamera.configDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null, "Proses Simpan data Berhasil..");
            tampilkan_data();
            kosongkan_form();
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());    
        }    
    }//GEN-LAST:event_btsimpanActionPerformed

    private void txtpencarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpencarianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpencarianActionPerformed

    private void bthapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bthapusActionPerformed
        // TODO add your handling code here:
        tabelpelanggan.setValueAt("", tabelpelanggan.getSelectedRow(), 0);
        tabelpelanggan.setValueAt("", tabelpelanggan.getSelectedRow(), 1);
        tabelpelanggan.setValueAt("", tabelpelanggan.getSelectedRow(), 2);
        tabelpelanggan.setValueAt("", tabelpelanggan.getSelectedRow(), 3);
        tabelpelanggan.setValueAt("", tabelpelanggan.getSelectedRow(), 4);
        tabelpelanggan.setValueAt("", tabelpelanggan.getSelectedRow(), 5);
        tabelpelanggan.setValueAt("", tabelpelanggan.getSelectedRow(), 6);
        tabelpelanggan.setValueAt("", tabelpelanggan.getSelectedRow(), 7);
        tabelpelanggan.setValueAt("", tabelpelanggan.getSelectedRow(), 8);
        tabelpelanggan.setValueAt("", tabelpelanggan.getSelectedRow(), 9);
        
    }//GEN-LAST:event_bthapusActionPerformed

    private void cbjeniskameraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbjeniskameraActionPerformed
        // TODO add your handling code here:
        String camera= cbjeniskamera.getSelectedItem().toString();
        if (camera.equalsIgnoreCase("Pilih Jenis")) {
            txthargasewa.setText("");
        } else if (camera.equalsIgnoreCase("CANON 60D")) {
            txthargasewa.setText("20000");
        } else if (camera.equalsIgnoreCase("CANON 1100D")) {
            txthargasewa.setText("15000");
        } else if (camera.equalsIgnoreCase("CANON 5D Mark II")) {
            txthargasewa.setText("40000");
        } else if (camera.equalsIgnoreCase("CANON 7D")) {
            txthargasewa.setText("35000");
        } else if (camera.equalsIgnoreCase("NIKON D3200")) {
            txthargasewa.setText("20000");
        } else if (camera.equalsIgnoreCase("NIKON D5200")) {
            txthargasewa.setText("25000");
        } else if (camera.equalsIgnoreCase("CANON EOS M3")) {
            txthargasewa.setText("30000");
        } else if (camera.equalsIgnoreCase("SONY A6500")) {
            txthargasewa.setText("45000");
        } else if (camera.equalsIgnoreCase("SONY A6400")) {
            txthargasewa.setText("35000");
        }
        
    }//GEN-LAST:event_cbjeniskameraActionPerformed

    private void txtpencarianKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpencarianKeyReleased
        // TODO add your handling code here:
        tampilkan_data();
    }//GEN-LAST:event_txtpencarianKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pelanggan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btbaru;
    private javax.swing.JButton bthapus;
    private javax.swing.JButton bthitung;
    private javax.swing.JButton btkeluar;
    private javax.swing.JButton btsimpan;
    private javax.swing.JComboBox<String> cbjeniskamera;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelpelanggan;
    private javax.swing.JTextField txtalamat;
    private javax.swing.JTextField txthargasewa;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtnohp;
    private javax.swing.JTextField txtpencarian;
    private javax.swing.JTextField txttotalharga;
    private javax.swing.JTextField txtwaktusewa;
    // End of variables declaration//GEN-END:variables

}
